language: node_js
node_js:
- 12
deploy:
  provider: heroku
  api_key:
    secure: Xia3UKi6iFGaHMGdHmo1NhEYnv6pGP+OoAW8eM86h7+HEYT17XEh3IrItX7k838bMHGrxr5ie3uJhFoamPvoMgcG9CtmdIFPHQexA3JWmQKCTI3CTCxbi07qxAYSu3wDoEa0AiRUpBJozCyo6VNPfg7q2LLEj9sATJQbE477xoEdNrJFrpapBZ4ejD+3sanaiQzIDStXABaWlZsLkxiEBwEwe5j1kcUtZHwpJSTiQfu0soVO4Pcvr/JMg31IQtdo2k1zAHPGe/p7QohKgkGR7KEeYov6OrGjQ8E02jJQfb1L/oVa1d7NiqNopcOSeXwTWnfzl/RbVCmzvYn1lG9huL56MCDOI5GMntj8lu6wqViGU4eLfuuovJtHkQiTNVk5src/OtbaXTjSS0FgwfBt8kIAVI63uj7CcZOZnhM8FMjoTuxzleQYdn1F0ubXO5VNPkwvEjm3gKojJAQjP5QL4aNk4GqOb42Kvh1gg3pZtW5Zxw2zhUBljrvfApgekr7qi/0LXQ9INKOEBZWLzH4WJrRIqHyJbThSi42n8mIPpGlF7/G/6aVpLY50/ZPld6h289qMaHj1azHGXyMfKUTJN5d3fRDaZT38EPxMU4XejhCmBWuZ7L//FqTAKBbYVVm1vNdF4msiZTaJNyfr+auFoQXbWVWD9kX2rvOAGKZynCk=
